# Use an official Node.js image as the base image
FROM node:18.19.0

# Set the working directory in the container
WORKDIR /app

# Copy the entire application to the container
COPY . /app

# Install dependencies
RUN npm install