version: "3.9"
name: stocken-frontend
services:
  nuxt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: nuxt
    networks:
      - networkfront
    command: sh -c "npm run build && node .output/server/index.mjs"
    volumes:
      - ..:/app
    environment:
      NODE_ENV: production
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      - networkfront
    ports: 
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nuxt

networks:
  networkfront:
    driver: bridge
    name: networkFront